version: "2.4"
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_HEAP_SIZE: 96
    cpu_shares: 128
    cpu_quota: 50000
    mem_reservation: 96m
    mem_limit: 128m

  kafka:
    image: bitnami/kafka
    ports:
      - 29092:29092
    environment:
      # KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092, PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_NUM_NETWORK_THREADS: 3
      # KAFKA_NUM_IO_THREADS: 3
      KAFKA_HEAP_OPTS: -Xmx512m -Xms512m
    depends_on:
      - zookeeper
    cpu_shares: 1024
    cpu_quota: 50000
    mem_reservation: 512m
    mem_limit: 640m

  cluster-statistics:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    ports:
      - 8081:8081
    command:
      [
        "job-cluster",
        "-j",
        "ch.ethz.infk.dspa.App",
        "-Djobmanager.rpc.address=cluster-statistics",
        "-Dparallelism.default=$TASK_PARALLELISM",
        "-kafkaserver",
        "kafka:9092",
        "-analyticstype",
        "activeposts",
        "-configpath",
        "/opt/config.properties",
        "-staticpath",
        "/opt/tables/",
        "-maxdelaysec",
        "$MAXDELAYSEC",
      ]
    volumes:
      - $SOURCE_DIRECTORY/social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - $SOURCE_DIRECTORY/data/$DATA_DIRECTORY/tables/:/opt/tables:ro
    cpu_shares: 1024
    cpu_quota: 70000
    mem_reservation: 512m
    mem_limit: 768m

  task-statistics:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    command: ["task-manager", "-Djobmanager.rpc.address=cluster-statistics"]
    volumes:
      - $SOURCE_DIRECTORY/social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - $SOURCE_DIRECTORY/data/$DATA_DIRECTORY/tables/:/opt/tables:ro
    depends_on:
      - cluster-statistics
    cpu_shares: 1024
    cpu_quota: 70000
    mem_reservation: 1024m
    mem_limit: 1280m

  cluster-recommendations:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    ports:
      - 8082:8081
    command:
      [
        "job-cluster",
        "-j",
        "ch.ethz.infk.dspa.App",
        "-Djobmanager.rpc.address=cluster-recommendations",
        "-Dparallelism.default=$TASK_PARALLELISM",
        "-kafkaserver",
        "kafka:9092",
        "-analyticstype",
        "recommendations",
        "-configpath",
        "/opt/config.properties",
        "-staticpath",
        "/opt/tables/",
        "-maxdelaysec",
        "$MAXDELAYSEC",
      ]
    volumes:
      - $SOURCE_DIRECTORY/social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - $SOURCE_DIRECTORY/data/$DATA_DIRECTORY/tables/:/opt/tables:ro
    cpu_shares: 1024
    cpu_quota: 70000
    mem_reservation: 512m
    mem_limit: 768m

  task-recommendations:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    command:
      ["task-manager", "-Djobmanager.rpc.address=cluster-recommendations"]
    volumes:
      - $SOURCE_DIRECTORY/social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - $SOURCE_DIRECTORY/data/$DATA_DIRECTORY/tables/:/opt/tables:ro
    depends_on:
      - cluster-recommendations
    cpu_shares: 1024
    cpu_quota: 70000
    mem_reservation: 1024m
    mem_limit: 1280m

  cluster-anomalies:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    ports:
      - 8083:8081
    command:
      [
        "job-cluster",
        "-j",
        "ch.ethz.infk.dspa.App",
        "-Djobmanager.rpc.address=cluster-anomalies",
        "-Dparallelism.default=$TASK_PARALLELISM",
        "-kafkaserver",
        "kafka:9092",
        "-analyticstype",
        "anomalies",
        "-configpath",
        "/opt/config.properties",
        "-staticpath",
        "/opt/tables/",
        "-maxdelaysec",
        "$MAXDELAYSEC",
      ]
    volumes:
      - $SOURCE_DIRECTORY/social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - $SOURCE_DIRECTORY/data/$DATA_DIRECTORY/tables/:/opt/tables:ro
    cpu_shares: 1024
    cpu_quota: 70000
    mem_reservation: 512m
    mem_limit: 768m

  task-anomalies:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    command: ["task-manager", "-Djobmanager.rpc.address=cluster-anomalies"]
    volumes:
      - $SOURCE_DIRECTORY/social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - $SOURCE_DIRECTORY/data/$DATA_DIRECTORY/tables/:/opt/tables:ro
    depends_on:
      - cluster-anomalies
    cpu_shares: 1024
    cpu_quota: 70000
    mem_reservation: 1024m
    mem_limit: 1280m

  producer-post:
    build:
      context: .
      dockerfile: stream-producer/Dockerfile
    entrypoint: ["/wait-for.sh", "$TASK", "java", "-jar", "/opt/producer.jar"]
    command:
      [
        "-file",
        "/data/$DATA_DIRECTORY/streams/post_event_stream_cleaned.csv",
        "-schema",
        "/data/schema/avro/post.avsc",
        "-topic",
        "post",
        "-kafkaserver",
        "kafka:9092",
        "-speedup",
        "$SPEEDUP",
        "-rdelay",
        "$MAXDELAYSEC",
        "-sdelay",
        "$SDELAY",
        "-seed",
        "1",
        "-worker",
        "1",
        "-start",
        "$PRODUCER_SYNC_TS",
      ]
    volumes:
      - $SOURCE_DIRECTORY/data:/data:ro
    depends_on:
      - kafka
    cpu_shares: 256
    cpu_quota: 25000
    mem_reservation: 128m
    mem_limit: 196m

  producer-like:
    build:
      context: .
      dockerfile: stream-producer/Dockerfile
    entrypoint: ["/wait-for.sh", "$TASK", "java", "-jar", "/opt/producer.jar"]
    command:
      [
        "-file",
        "/data/$DATA_DIRECTORY/streams/likes_event_stream_cleaned.csv",
        "-schema",
        "/data/schema/avro/like.avsc",
        "-topic",
        "like",
        "-kafkaserver",
        "kafka:9092",
        "-speedup",
        "$SPEEDUP",
        "-rdelay",
        "$MAXDELAYSEC",
        "-sdelay",
        "$SDELAY",
        "-seed",
        "2",
        "-worker",
        "1",
        "-start",
        "$PRODUCER_SYNC_TS",
      ]
    volumes:
      - $SOURCE_DIRECTORY/data:/data:ro
    depends_on:
      - kafka
    cpu_shares: 256
    cpu_quota: 25000
    mem_reservation: 128m
    mem_limit: 196m

  producer-comment:
    build:
      context: .
      dockerfile: stream-producer/Dockerfile
    entrypoint: ["/wait-for.sh", "$TASK", "java", "-jar", "/opt/producer.jar"]
    command:
      [
        "-file",
        "/data/$DATA_DIRECTORY/streams/comment_event_stream_cleaned.csv",
        "-schema",
        "/data/schema/avro/comment.avsc",
        "-topic",
        "comment",
        "-kafkaserver",
        "kafka:9092",
        "-speedup",
        "$SPEEDUP",
        "-rdelay",
        "$MAXDELAYSEC",
        "-sdelay",
        "$SDELAY",
        "-seed",
        "3",
        "-worker",
        "1",
        "-start",
        "$PRODUCER_SYNC_TS",
      ]
    volumes:
      - $SOURCE_DIRECTORY/data:/data:ro
    depends_on:
      - kafka
    cpu_shares: 256
    cpu_quota: 25000
    mem_reservation: 128m
    mem_limit: 196m

  kafka-web:
    build: web/kafkaui
    ports:
      - 8080:8080
    volumes:
      - web-data:/app/data
    depends_on:
      - kafka
    cpu_shares: 256
    cpu_quota: 10000
    mem_limit: 128m

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./web/redis.conf:/opt/bitnami/redis/etc/redis.conf:ro
    cpu_shares: 1024
    cpu_quota: 40000
    mem_reservation: 256m
    mem_limit: 512m

  web:
    build: web
    ports:
      - 4000:4000
    environment:
      KAFKA_URL: "kafka:9092"
      REDIS_HOST: "redis"
    depends_on:
      - kafka
      - redis

volumes:
  web-data:
