version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka
    ports:
      - 29092:29092
    environment:
      # KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENERS: PLAINTEXT://:9092, PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 3
      KAFKA_HEAP_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      - zookeeper

  kafka-web:
    build: web
    ports:
      - 8080:8080
    volumes:
      - web-data:/app/data
    depends_on:
      - kafka

  cluster-statistics:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    ports:
      - 8081:8081
    command:
      [
        "job-cluster",
        "-j",
        "ch.ethz.infk.dspa.App",
        "-Djobmanager.rpc.address=cluster-statistics",
        "-Dparallelism.default=2",
        "-kafkaserver",
        "kafka:9092",
        "-analyticstype",
        "activeposts",
        "-configpath",
        "/opt/config.properties",
        "-staticpath",
        "/opt/tables/",
        "-maxdelaysec",
        "600",
      ]
    volumes:
      - ./social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - ./data/1k-users-sorted/tables/:/opt/tables:ro

  task-statistics:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    command: ["task-manager", "-Djobmanager.rpc.address=cluster-statistics"]
    volumes:
      - ./social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - ./data/1k-users-sorted/tables/:/opt/tables:ro
    depends_on:
      - cluster-statistics

  cluster-recommendations:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    ports:
      - 8082:8081
    command:
      [
        "job-cluster",
        "-j",
        "ch.ethz.infk.dspa.App",
        "-Djobmanager.rpc.address=cluster-recommendations",
        "-Dparallelism.default=2",
        "-kafkaserver",
        "kafka:9092",
        "-analyticstype",
        "recommendations",
        "-configpath",
        "/opt/config.properties",
        "-staticpath",
        "/opt/tables/",
        "-maxdelaysec",
        "600",
      ]
    volumes:
      - ./social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - ./data/1k-users-sorted/tables/:/opt/tables:ro

  task-recommendations:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    command:
      ["task-manager", "-Djobmanager.rpc.address=cluster-recommendations"]
    volumes:
      - ./social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - ./data/1k-users-sorted/tables/:/opt/tables:ro
    depends_on:
      - cluster-recommendations

  cluster-anomalies:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    ports:
      - 8083:8081
    command:
      [
        "job-cluster",
        "-j",
        "ch.ethz.infk.dspa.App",
        "-Djobmanager.rpc.address=cluster-anomalies",
        "-Dparallelism.default=2",
        "-kafkaserver",
        "kafka:9092",
        "-analyticstype",
        "anomalies",
        "-configpath",
        "/opt/config.properties",
        "-staticpath",
        "/opt/tables/",
        "-maxdelaysec",
        "600",
      ]
    volumes:
      - ./social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - ./data/1k-users-sorted/tables/:/opt/tables:ro

  task-anomalies:
    build:
      context: .
      dockerfile: social-network-analysis/Dockerfile
    command: ["task-manager", "-Djobmanager.rpc.address=cluster-anomalies"]
    volumes:
      - ./social-network-analysis/src/main/java/ch/ethz/infk/dspa/config.properties:/opt/config.properties:ro
      - ./data/1k-users-sorted/tables/:/opt/tables:ro
    depends_on:
      - cluster-anomalies

  producer-post:
    build:
      context: .
      dockerfile: stream-producer/Dockerfile
    command:
      [
        "java",
        "-jar",
        "/opt/producer.jar",
        "-file",
        "/data/1k-users-sorted/streams/post_event_stream_cleaned.csv",
        "-schema",
        "/data/schema/avro/post.avsc",
        "-topic",
        "post",
        "-kafkaserver",
        "kafka:9092",
        "-speedup",
        "20",
        "-rdelay",
        "5",
        "-sdelay",
        "600",
        "-seed",
        "1",
        "-worker",
        "1",
      ]
    volumes:
      - ./data:/data:ro

  producer-like:
    build:
      context: .
      dockerfile: stream-producer/Dockerfile
    command:
      [
        "java",
        "-jar",
        "/opt/producer.jar",
        "-file",
        "/data/1k-users-sorted/streams/likes_event_stream_cleaned.csv",
        "-schema",
        "/data/schema/avro/like.avsc",
        "-topic",
        "like",
        "-kafkaserver",
        "kafka:9092",
        "-speedup",
        "20",
        "-rdelay",
        "5",
        "-sdelay",
        "600",
        "-seed",
        "2",
        "-worker",
        "1",
      ]
    volumes:
      - ./data:/data:ro

  producer-comment:
    build:
      context: .
      dockerfile: stream-producer/Dockerfile
    command:
      [
        "java",
        "-jar",
        "/opt/producer.jar",
        "-file",
        "/data/1k-users-sorted/streams/comment_event_stream_cleaned.csv",
        "-schema",
        "/data/schema/avro/comment.avsc",
        "-topic",
        "comment",
        "-kafkaserver",
        "kafka:9092",
        "-speedup",
        "20",
        "-rdelay",
        "5",
        "-sdelay",
        "600",
        "-seed",
        "3",
        "-worker",
        "1",
      ]
    volumes:
      - ./data:/data:ro

volumes:
  web-data:
