version: "3"
services:
  kafka:
    # https://github.com/Landoop/fast-data-dev
    image: landoop/fast-data-dev
    network_mode: "host"
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
