version: "3"
services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      # CONSUMER_ROOT: social-network-analysis
      # JAR_NAME: social-network-analysis-1.0.0.jar
      # FLINK_VERSION: 1.7.2
      # SCALA_VERSION: 2.11
