version: "3"
services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      # CONSUMER_ROOT: social-network-analysis
      # JAR_NAME: social-network-analysis-1.0.0.jar
      # FLINK_VERSION: 1.7.2
      # SCALA_VERSION: 2.11
    depends_on:
      - kafka

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka_web:
    build: web
    ports:
      - 8080:8080
    volumes:
      - web-data:/app/data
    depends_on:
      - kafka

volumes:
  web-data:
