version: "3"
services:
  kafka:
    # https://github.com/Landoop/fast-data-dev
    image: landoop/fast-data-dev
    # network_mode: "host"
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    environment:
      ADV_HOST: localhost
      EULA: https://dl.lenses.stream/d/?id=087b84d0-723d-49b8-afd0-1d8d23f03e67
